# Generated by Django 4.2.11 on 2024-04-10 21:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('despesas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategoria',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategorias', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pagamentoparcelado',
            name='cartao_credito',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='despesas.cartaocredito'),
        ),
        migrations.AddField(
            model_name='pagamentoparcelado',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='despesas.categoria'),
        ),
        migrations.AddField(
            model_name='pagamentoparcelado',
            name='conta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='despesas.conta'),
        ),
        migrations.AddField(
            model_name='pagamentoparcelado',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='despesa',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='despesas.categoria'),
        ),
        migrations.AddField(
            model_name='despesa',
            name='conta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='despesas.conta'),
        ),
        migrations.AddField(
            model_name='despesa',
            name='subcategoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='despesas.subcategoria'),
        ),
        migrations.AddField(
            model_name='despesa',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='conta',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cheque',
            name='conta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='despesas.conta'),
        ),
        migrations.AddField(
            model_name='cheque',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='categoria',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categorias', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cartaocredito',
            name='conta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='despesas.conta'),
        ),
        migrations.AddField(
            model_name='cartaocredito',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
