# Generated by Django 4.2.11 on 2024-04-11 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('despesas', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='despesa',
            options={'ordering': ['-data'], 'verbose_name_plural': 'Despesas'},
        ),
    ]
