# Generated by Django 4.2.11 on 2024-04-12 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('despesas', '0004_cheque_valor_currency_despesa_valor_currency_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conta',
            options={'ordering': ['nome'], 'verbose_name_plural': 'Contas'},
        ),
    ]
