# Generated by Django 4.2.11 on 2024-04-19 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('despesas', '0005_alter_conta_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despesa',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='despesas.categoria'),
        ),
        migrations.AlterField(
            model_name='despesa',
            name='subcategoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='despesas.subcategoria'),
        ),
    ]
