# Generated by Django 4.2.11 on 2024-04-22 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('despesas', '0006_alter_despesa_categoria_alter_despesa_subcategoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despesa',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='despesas.categoria'),
        ),
        migrations.AlterField(
            model_name='despesa',
            name='subcategoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='despesas.subcategoria'),
        ),
    ]
